In [2]:
mamba install pandas

mambajs 0.21.4

Specs: xeus-python, numpy, matplotlib, pillow, ipywidgets>=8.1.6, ipyleaflet, scipy, pandas
Channels: emscripten-forge-4x, conda-forge

Solving environment...
Solving took 7.774 seconds
  Name           Version  Build                Channel
--------------------------------------------------------------------
+ pandas         3.0.5    np23py313h1e705a5_0  emscripten-forge-4x
+ python-tzdata  2026.3   pyhd8ed1ab_0         conda-forge
- pip            26.1.2   pyh145f28c_0         conda-forge

In [3]:
import pandas as pd
pd.read_csv('healthcare.csv')
pd

In [6]:
import pandas as pd
df = pd.read_csv('healthcare.csv')
df

,Patient Id,Patient Admission Date,Patient Admission Time,patient name,Patient Gender,Patient Age,Department Referral,Patient Admission Flag,Patient Satisfaction Score,Patient Waittime
0,780-96-6113,09-09-2024,9:25:00 AM,W. Breede,Female,63,NaN,Not Admission,5.0,32
1,714-35-6722,09-09-2024,4:42:00 PM,Y. Baldetti,Male,31,xray,Not Admission,NaN,22
2,571-85-3714,09-09-2024,12:14:00 AM,M. Semerad,Male,75,xray,Not Admission,NaN,16
3,404-43-9499,09-09-2024,8:33:00 PM,K. Blaydes,Male,79,xray,Admission,7.0,38
4,552-51-5855,09-09-2024,7:25:00 PM,F. Dickerson,Female,24,xray,Admission,7.0,36
...,...,...,...,...,...,...,...,...,...,...
9211,353-25-3957,01-01-2024,11:01:00 PM,S. Levermore,Male,19,Cardiology,Not Admission,NaN,34
9212,608-47-0337,01-01-2024,5:25:00 PM,R. Boyle,Female,22,Orthopedics,Admission,NaN,45
9213,716-90-5923,01-01-2024,11:42:00 AM,V. Seadon,Female,8,NaN,Admission,NaN,21
9214,641-52-3173,01-01-2024,4:59:00 AM,L. Harford,Female,37,NaN,Not Admission,5.0,10
9215,390-79-5650,01-01-2024,5:33:00 PM,E. Skerritt,Male,59,NaN,Not Admission,NaN,47

In [7]:
df.head()

,Patient Id,Patient Admission Date,Patient Admission Time,patient name,Patient Gender,Patient Age,Department Referral,Patient Admission Flag,Patient Satisfaction Score,Patient Waittime
0,780-96-6113,09-09-2024,9:25:00 AM,W. Breede,Female,63,NaN,Not Admission,5.0,32
1,714-35-6722,09-09-2024,4:42:00 PM,Y. Baldetti,Male,31,xray,Not Admission,NaN,22
2,571-85-3714,09-09-2024,12:14:00 AM,M. Semerad,Male,75,xray,Not Admission,NaN,16
3,404-43-9499,09-09-2024,8:33:00 PM,K. Blaydes,Male,79,xray,Admission,7.0,38
4,552-51-5855,09-09-2024,7:25:00 PM,F. Dickerson,Female,24,xray,Admission,7.0,36

In [8]:
df.describe

<bound method NDFrame.describe of        Patient Id Patient Admission Date Patient Admission Time  patient name  \
0     780-96-6113             09-09-2024             9:25:00 AM     W. Breede
1     714-35-6722             09-09-2024             4:42:00 PM   Y. Baldetti
2     571-85-3714             09-09-2024            12:14:00 AM    M. Semerad
3     404-43-9499             09-09-2024             8:33:00 PM    K. Blaydes
4     552-51-5855             09-09-2024             7:25:00 PM  F. Dickerson
...           ...                    ...                    ...           ...
9211  353-25-3957             01-01-2024            11:01:00 PM  S. Levermore
9212  608-47-0337             01-01-2024             5:25:00 PM      R. Boyle
9213  716-90-5923             01-01-2024            11:42:00 AM     V. Seadon
9214  641-52-3173             01-01-2024             4:59:00 AM    L. Harford
9215  390-79-5650             01-01-2024             5:33:00 PM   E. Skerritt

     Patient Gender  Patient Age Department Referral Patient Admission Flag  \
0            Female           63                 NaN          Not Admission
1              Male           31                xray          Not Admission
2              Male           75                xray          Not Admission
3              Male           79                xray              Admission
4            Female           24                xray              Admission
...             ...          ...                 ...                    ...
9211           Male           19          Cardiology          Not Admission
9212         Female           22         Orthopedics              Admission
9213         Female            8                 NaN              Admission
9214         Female           37                 NaN          Not Admission
9215           Male           59                 NaN          Not Admission

      Patient Satisfaction Score  Patient Waittime
0                            5.0                32
1                            NaN                22
2                            NaN                16
3                            7.0                38
4                            7.0                36
...                          ...               ...
9211                         NaN                34
9212                         NaN                45
9213                         NaN                21
9214                         5.0                10
9215                         NaN                47

[9216 rows x 10 columns]>

In [10]:
df.isnull().sum()

Patient Id                       0
Patient Admission Date           0
Patient Admission Time           0
patient name                     0
Patient Gender                   0
Patient Age                      0
Department Referral           5008
Patient Admission Flag           0
Patient Satisfaction Score    6696
Patient Waittime                 0
dtype: int64

In [13]:
df = df .dropna(subset=['Department Referral'])

In [15]:
df.isnull().sum()

Patient Id                       0
Patient Admission Date           0
Patient Admission Time           0
patient name                     0
Patient Gender                   0
Patient Age                      0
Department Referral              0
Patient Admission Flag           0
Patient Satisfaction Score    3039
Patient Waittime                 0
dtype: int64

In [16]:
df = df .dropna(subset=['Patient Satisfaction Score'])

In [17]:
df.isnull().sum()

Patient Id                    0
Patient Admission Date        0
Patient Admission Time        0
patient name                  0
Patient Gender                0
Patient Age                   0
Department Referral           0
Patient Admission Flag        0
Patient Satisfaction Score    0
Patient Waittime              0
dtype: int64

In [19]:
df=pd.read_csv('healthcare.csv')
df

,Patient Id,Patient Admission Date,Patient Admission Time,patient name,Patient Gender,Patient Age,Department Referral,Patient Admission Flag,Patient Satisfaction Score,Patient Waittime
0,780-96-6113,09-09-2024,9:25:00 AM,W. Breede,Female,63,NaN,Not Admission,5.0,32
1,714-35-6722,09-09-2024,4:42:00 PM,Y. Baldetti,Male,31,xray,Not Admission,NaN,22
2,571-85-3714,09-09-2024,12:14:00 AM,M. Semerad,Male,75,xray,Not Admission,NaN,16
3,404-43-9499,09-09-2024,8:33:00 PM,K. Blaydes,Male,79,xray,Admission,7.0,38
4,552-51-5855,09-09-2024,7:25:00 PM,F. Dickerson,Female,24,xray,Admission,7.0,36
...,...,...,...,...,...,...,...,...,...,...
9211,353-25-3957,01-01-2024,11:01:00 PM,S. Levermore,Male,19,Cardiology,Not Admission,NaN,34
9212,608-47-0337,01-01-2024,5:25:00 PM,R. Boyle,Female,22,Orthopedics,Admission,NaN,45
9213,716-90-5923,01-01-2024,11:42:00 AM,V. Seadon,Female,8,NaN,Admission,NaN,21
9214,641-52-3173,01-01-2024,4:59:00 AM,L. Harford,Female,37,NaN,Not Admission,5.0,10
9215,390-79-5650,01-01-2024,5:33:00 PM,E. Skerritt,Male,59,NaN,Not Admission,NaN,47

In [20]:
df.columns=df.columns.str.lower()
df.columns=df.columns.str.replace(' ','_')
df

,patient_id,patient_admission_date,patient_admission_time,patient_name,patient_gender,patient_age,department_referral,patient_admission_flag,patient_satisfaction_score,patient_waittime
0,780-96-6113,09-09-2024,9:25:00 AM,W. Breede,Female,63,NaN,Not Admission,5.0,32
1,714-35-6722,09-09-2024,4:42:00 PM,Y. Baldetti,Male,31,xray,Not Admission,NaN,22
2,571-85-3714,09-09-2024,12:14:00 AM,M. Semerad,Male,75,xray,Not Admission,NaN,16
3,404-43-9499,09-09-2024,8:33:00 PM,K. Blaydes,Male,79,xray,Admission,7.0,38
4,552-51-5855,09-09-2024,7:25:00 PM,F. Dickerson,Female,24,xray,Admission,7.0,36
...,...,...,...,...,...,...,...,...,...,...
9211,353-25-3957,01-01-2024,11:01:00 PM,S. Levermore,Male,19,Cardiology,Not Admission,NaN,34
9212,608-47-0337,01-01-2024,5:25:00 PM,R. Boyle,Female,22,Orthopedics,Admission,NaN,45
9213,716-90-5923,01-01-2024,11:42:00 AM,V. Seadon,Female,8,NaN,Admission,NaN,21
9214,641-52-3173,01-01-2024,4:59:00 AM,L. Harford,Female,37,NaN,Not Admission,5.0,10
9215,390-79-5650,01-01-2024,5:33:00 PM,E. Skerritt,Male,59,NaN,Not Admission,NaN,47

In [22]:
df.columns

Index(['patient_id', 'patient_admission_date', 'patient_admission_time',
       'patient_name', 'patient_gender', 'patient_age', 'department_referral',
       'patient_admission_flag', 'patient_satisfaction_score',
       'patient_waittime'],
      dtype='str')