In [2]:
mamba install pandas

mambajs 0.21.4

Specs: xeus-python, numpy, matplotlib, pillow, ipywidgets>=8.1.6, ipyleaflet, scipy, pandas
Channels: emscripten-forge-4x, conda-forge

Solving environment...
Solving took 4.960 seconds
  Name           Version  Build                Channel
--------------------------------------------------------------------
+ pandas         3.0.5    np23py313h1e705a5_0  emscripten-forge-4x
+ python-tzdata  2026.3   pyhd8ed1ab_0         conda-forge
- pip            26.1.2   pyh145f28c_0         conda-forge

In [3]:
import pandas as pd
df =pd.read_csv("Healthcare2.csv")
df

,Event_ID,Case_ID,Patient_ID,Event_Order,Activity,Department,Event_Date,Event_Time,Timestamp,Patient_Gender,Patient_Age,Patient_Race,Department_Referral,Admission_Flag,Previous_Activity,Waiting_Time_Min,Event_Status,Rework_Reason
0,E000001,C00001,P00001,1,Registration,Front Desk,13-10-2026,10:35:00,13-10-2026 10:35,Female,19,Hispanic,Ambulance,0,NaN,0,Completed,NaN
1,E000002,C00001,P00001,2,Triage,Emergency Department,13-10-2026,10:55:00,13-10-2026 10:55,Female,19,Hispanic,Ambulance,0,Registration,20,Completed,NaN
2,E000003,C00001,P00001,3,Doctor,Emergency Department,13-10-2026,11:55:00,13-10-2026 11:55,Female,19,Hispanic,Ambulance,0,Triage,60,Completed,NaN
3,E000004,C00001,P00001,4,Pharmacy,Pharmacy,13-10-2026,12:14:00,13-10-2026 12:14,Female,19,Hispanic,Ambulance,0,Doctor,19,Completed,NaN
4,E000005,C00001,P00001,5,Discharge,Emergency Department,13-10-2026,12:47:00,13-10-2026 12:47,Female,19,Hispanic,Ambulance,0,Pharmacy,33,Completed,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
24995,E024996,C04657,P04657,6,Discharge,Emergency Department,31-01-2026,2:48:00,31-01-2026 02:48,Male,28,White,Self,0,Doctor,28,Completed,NaN
24996,E024997,C04658,P04658,1,Registration,Front Desk,17-04-2026,7:01:00,17-04-2026 07:01,Male,56,Other,Ambulance,0,NaN,0,Completed,NaN
24997,E024998,C04658,P04658,2,Triage,Emergency Department,17-04-2026,7:32:00,17-04-2026 07:32,Male,56,Other,Ambulance,0,Registration,31,Completed,NaN
24998,E024999,C04658,P04658,3,Doctor,Emergency Department,17-04-2026,8:23:00,17-04-2026 08:23,Male,56,Other,Ambulance,0,Triage,51,Completed,NaN
24999,E025000,C04658,P04658,4,Discharge,Emergency Department,17-04-2026,8:53:00,17-04-2026 08:53,Male,56,Other,Ambulance,0,Doctor,30,Completed,NaN

In [5]:
df.head()
df.shape
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 25000 entries, 0 to 24999
Data columns (total 18 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Event_ID             25000 non-null  str
 1   Case_ID              25000 non-null  str
 2   Patient_ID           25000 non-null  str
 3   Event_Order          25000 non-null  int64
 4   Activity             25000 non-null  str
 5   Department           25000 non-null  str
 6   Event_Date           25000 non-null  str
 7   Event_Time           25000 non-null  str
 8   Timestamp            25000 non-null  str
 9   Patient_Gender       25000 non-null  str
 10  Patient_Age          25000 non-null  int64
 11  Patient_Race         25000 non-null  str
 12  Department_Referral  25000 non-null  str
 13  Admission_Flag       25000 non-null  int64
 14  Previous_Activity    20342 non-null  str
 15  Waiting_Time_Min     25000 non-null  int64
 16  Event_Status         25000 non-null  str
 17  Rework_Reason        400 non-null    str
dtypes: int64(4), str(14)
memory usage: 2.1 MB

In [6]:
df.isnull().sum()

Event_ID                   0
Case_ID                    0
Patient_ID                 0
Event_Order                0
Activity                   0
Department                 0
Event_Date                 0
Event_Time                 0
Timestamp                  0
Patient_Gender             0
Patient_Age                0
Patient_Race               0
Department_Referral        0
Admission_Flag             0
Previous_Activity       4658
Waiting_Time_Min           0
Event_Status               0
Rework_Reason          24600
dtype: int64

In [7]:
df= df.drop(columns=["Patient_Race","Rework_Reason"])
df

,Event_ID,Case_ID,Patient_ID,Event_Order,Activity,Department,Event_Date,Event_Time,Timestamp,Patient_Gender,Patient_Age,Department_Referral,Admission_Flag,Previous_Activity,Waiting_Time_Min,Event_Status
0,E000001,C00001,P00001,1,Registration,Front Desk,13-10-2026,10:35:00,13-10-2026 10:35,Female,19,Ambulance,0,NaN,0,Completed
1,E000002,C00001,P00001,2,Triage,Emergency Department,13-10-2026,10:55:00,13-10-2026 10:55,Female,19,Ambulance,0,Registration,20,Completed
2,E000003,C00001,P00001,3,Doctor,Emergency Department,13-10-2026,11:55:00,13-10-2026 11:55,Female,19,Ambulance,0,Triage,60,Completed
3,E000004,C00001,P00001,4,Pharmacy,Pharmacy,13-10-2026,12:14:00,13-10-2026 12:14,Female,19,Ambulance,0,Doctor,19,Completed
4,E000005,C00001,P00001,5,Discharge,Emergency Department,13-10-2026,12:47:00,13-10-2026 12:47,Female,19,Ambulance,0,Pharmacy,33,Completed
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
24995,E024996,C04657,P04657,6,Discharge,Emergency Department,31-01-2026,2:48:00,31-01-2026 02:48,Male,28,Self,0,Doctor,28,Completed
24996,E024997,C04658,P04658,1,Registration,Front Desk,17-04-2026,7:01:00,17-04-2026 07:01,Male,56,Ambulance,0,NaN,0,Completed
24997,E024998,C04658,P04658,2,Triage,Emergency Department,17-04-2026,7:32:00,17-04-2026 07:32,Male,56,Ambulance,0,Registration,31,Completed
24998,E024999,C04658,P04658,3,Doctor,Emergency Department,17-04-2026,8:23:00,17-04-2026 08:23,Male,56,Ambulance,0,Triage,51,Completed
24999,E025000,C04658,P04658,4,Discharge,Emergency Department,17-04-2026,8:53:00,17-04-2026 08:53,Male,56,Ambulance,0,Doctor,30,Completed

In [8]:
df.isnull().sum()

Event_ID                  0
Case_ID                   0
Patient_ID                0
Event_Order               0
Activity                  0
Department                0
Event_Date                0
Event_Time                0
Timestamp                 0
Patient_Gender            0
Patient_Age               0
Department_Referral       0
Admission_Flag            0
Previous_Activity      4658
Waiting_Time_Min          0
Event_Status              0
dtype: int64

In [9]:
df.to_csv("Healthsystem.csv",index=False)

In [10]:
df=pd.read_csv("Healthsystem.csv")
df

,Event_ID,Case_ID,Patient_ID,Event_Order,Activity,Department,Event_Date,Event_Time,Timestamp,Patient_Gender,Patient_Age,Department_Referral,Admission_Flag,Previous_Activity,Waiting_Time_Min,Event_Status
0,E000001,C00001,P00001,1,Registration,Front Desk,13-10-2026,10:35:00,13-10-2026 10:35,Female,19,Ambulance,0,NaN,0,Completed
1,E000002,C00001,P00001,2,Triage,Emergency Department,13-10-2026,10:55:00,13-10-2026 10:55,Female,19,Ambulance,0,Registration,20,Completed
2,E000003,C00001,P00001,3,Doctor,Emergency Department,13-10-2026,11:55:00,13-10-2026 11:55,Female,19,Ambulance,0,Triage,60,Completed
3,E000004,C00001,P00001,4,Pharmacy,Pharmacy,13-10-2026,12:14:00,13-10-2026 12:14,Female,19,Ambulance,0,Doctor,19,Completed
4,E000005,C00001,P00001,5,Discharge,Emergency Department,13-10-2026,12:47:00,13-10-2026 12:47,Female,19,Ambulance,0,Pharmacy,33,Completed
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
24995,E024996,C04657,P04657,6,Discharge,Emergency Department,31-01-2026,2:48:00,31-01-2026 02:48,Male,28,Self,0,Doctor,28,Completed
24996,E024997,C04658,P04658,1,Registration,Front Desk,17-04-2026,7:01:00,17-04-2026 07:01,Male,56,Ambulance,0,NaN,0,Completed
24997,E024998,C04658,P04658,2,Triage,Emergency Department,17-04-2026,7:32:00,17-04-2026 07:32,Male,56,Ambulance,0,Registration,31,Completed
24998,E024999,C04658,P04658,3,Doctor,Emergency Department,17-04-2026,8:23:00,17-04-2026 08:23,Male,56,Ambulance,0,Triage,51,Completed
24999,E025000,C04658,P04658,4,Discharge,Emergency Department,17-04-2026,8:53:00,17-04-2026 08:53,Male,56,Ambulance,0,Doctor,30,Completed

In [11]:
df.duplicated().sum()

np.int64(0)

In [12]:
df.duplicated().sum()

np.int64(0)

In [13]:
df["Event_ID"].duplicated().sum()

np.int64(0)

In [14]:
df = df.sort_values(
    by=["Case_ID", "Event_Order"])

In [15]:
df.groupby("Case_ID")["Activity"].apply(
    list
)

Case_ID
C00001    [Registration, Triage, Doctor, Pharmacy, Disch...
C00002    [Registration, Triage, Doctor, Pharmacy, Disch...
C00003    [Registration, Triage, Doctor, Pharmacy, Disch...
C00004    [Registration, Triage, Doctor, Pharmacy, Disch...
C00005    [Registration, Triage, Doctor, Pharmacy, Disch...
                                ...
C04654    [Registration, Triage, Doctor, Pharmacy, Disch...
C04655    [Registration, Triage, Doctor, Pharmacy, Disch...
C04656    [Registration, Triage, Doctor, Imaging, Triage...
C04657    [Registration, Triage, Doctor, Lab, Doctor, Di...
C04658            [Registration, Triage, Doctor, Discharge]
Name: Activity, Length: 4658, dtype: object

In [16]:
df[df["Waiting_Time_Min"] < 0]

Empty DataFrame
Columns: [Event_ID, Case_ID, Patient_ID, Event_Order, Activity, Department, Event_Date, Event_Time, Timestamp, Patient_Gender, Patient_Age, Department_Referral, Admission_Flag, Previous_Activity, Waiting_Time_Min, Event_Status]
Index: []

In [17]:
df = df.sort_values(
    by=["Case_ID", "Event_Order"]
)

In [18]:
df["Timestamp"] = pd.to_datetime(df["Timestamp"])

/tmp/xpython_42/3991263233.py:1: UserWarning: Parsing dates in %d-%m-%Y %H:%M format when dayfirst=False (the default) was specified. Pass `dayfirst=True` or specify a format to silence this warning.
  df["Timestamp"] = pd.to_datetime(df["Timestamp"])

In [19]:
df["Timestamp"] = pd.to_datetime(df["Timestamp"])

In [20]:
df = df.sort_values(
    by=["Case_ID", "Timestamp"]
)

In [21]:
df = df.sort_values(
    by=["Case_ID", "Timestamp"]
)

In [22]:
df["Waiting_Time_Min"].mean()

np.float64(27.16244)

In [23]:
df.groupby("Activity")[
    "Waiting_Time_Min"
].mean().sort_values(ascending=False)

Activity
Imaging         73.299000
Lab             65.815000
Doctor          44.791052
Triage          27.268683
Pharmacy        25.280540
Discharge       19.715328
Registration     0.000000
Name: Waiting_Time_Min, dtype: float64

In [24]:
df.groupby("Department")[
    "Waiting_Time_Min"
].mean()

Department
Emergency Department    31.692935
Front Desk               0.000000
Laboratory              65.815000
Pharmacy                25.280540
Radiology               73.299000
Name: Waiting_Time_Min, dtype: float64

In [25]:
case_wait = df.groupby("Case_ID")[
    "Waiting_Time_Min"
].sum()

In [26]:
activity_counts = df.groupby(
    ["Case_ID", "Activity"]
).size()

In [27]:
df.groupby(
    ["Department", "Department_Referral"]
).size()

Department            Department_Referral
Emergency Department  Ambulance              3231
                      General                3175
                      Primary Care           3113
                      Self                   3026
                      Specialist             3139
Front Desk            Ambulance               968
                      General                 942
                      Primary Care            923
                      Self                    894
                      Specialist              931
Laboratory            Ambulance                85
                      General                  80
                      Primary Care             74
                      Self                     77
                      Specialist               84
Pharmacy              Ambulance               698
                      General                 646
                      Primary Care            646
                      Self                    637
                      Specialist              631
Radiology             Ambulance               184
                      General                 199
                      Primary Care            200
                      Self                    210
                      Specialist              207
dtype: int64

In [28]:
df.groupby("Admission_Flag")[
    "Waiting_Time_Min"
].mean()

Admission_Flag
0    27.151183
1    27.213061
Name: Waiting_Time_Min, dtype: float64

In [29]:
process_df = df[
    ["Case_ID", "Activity", "Timestamp"]
].copy()

In [32]:
df= pd.read_csv("Healthcare2.csv")
df

,Event_ID,Case_ID,Patient_ID,Event_Order,Activity,Department,Event_Date,Event_Time,Timestamp,Patient_Gender,Patient_Age,Patient_Race,Department_Referral,Admission_Flag,Previous_Activity,Waiting_Time_Min,Event_Status,Rework_Reason
0,E000001,C00001,P00001,1,Registration,Front Desk,13-10-2026,10:35:00,13-10-2026 10:35,Female,19,Hispanic,Ambulance,0,NaN,0,Completed,NaN
1,E000002,C00001,P00001,2,Triage,Emergency Department,13-10-2026,10:55:00,13-10-2026 10:55,Female,19,Hispanic,Ambulance,0,Registration,20,Completed,NaN
2,E000003,C00001,P00001,3,Doctor,Emergency Department,13-10-2026,11:55:00,13-10-2026 11:55,Female,19,Hispanic,Ambulance,0,Triage,60,Completed,NaN
3,E000004,C00001,P00001,4,Pharmacy,Pharmacy,13-10-2026,12:14:00,13-10-2026 12:14,Female,19,Hispanic,Ambulance,0,Doctor,19,Completed,NaN
4,E000005,C00001,P00001,5,Discharge,Emergency Department,13-10-2026,12:47:00,13-10-2026 12:47,Female,19,Hispanic,Ambulance,0,Pharmacy,33,Completed,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
24995,E024996,C04657,P04657,6,Discharge,Emergency Department,31-01-2026,2:48:00,31-01-2026 02:48,Male,28,White,Self,0,Doctor,28,Completed,NaN
24996,E024997,C04658,P04658,1,Registration,Front Desk,17-04-2026,7:01:00,17-04-2026 07:01,Male,56,Other,Ambulance,0,NaN,0,Completed,NaN
24997,E024998,C04658,P04658,2,Triage,Emergency Department,17-04-2026,7:32:00,17-04-2026 07:32,Male,56,Other,Ambulance,0,Registration,31,Completed,NaN
24998,E024999,C04658,P04658,3,Doctor,Emergency Department,17-04-2026,8:23:00,17-04-2026 08:23,Male,56,Other,Ambulance,0,Triage,51,Completed,NaN
24999,E025000,C04658,P04658,4,Discharge,Emergency Department,17-04-2026,8:53:00,17-04-2026 08:53,Male,56,Other,Ambulance,0,Doctor,30,Completed,NaN

In [34]:
df.to_csv("Healthcare2.csv",index=False)