In [2]:
mamba install pandas
import pandas as pd
df = pd.read_csv('healthcare.csv')
df

mambajs 0.21.4

Specs: xeus-python, numpy, matplotlib, pillow, ipywidgets>=8.1.6, ipyleaflet, scipy, pandas
Channels: emscripten-forge-4x, conda-forge

Solving environment...
Solving took 4.471 seconds
  Name           Version  Build                Channel
--------------------------------------------------------------------
+ pandas         3.0.5    np23py313h1e705a5_0  emscripten-forge-4x
+ python-tzdata  2026.3   pyhd8ed1ab_0         conda-forge
- pip            26.1.2   pyh145f28c_0         conda-forge

,Patient Id,Patient Admission Date,Patient Admission Time,patient name,Patient Gender,Patient Age,Department Referral,Patient Admission Flag,Patient Satisfaction Score,Patient Waittime
0,780-96-6113,09-09-2024,9:25:00 AM,W. Breede,Female,63,NaN,Not Admission,5.0,32
1,714-35-6722,09-09-2024,4:42:00 PM,Y. Baldetti,Male,31,xray,Not Admission,NaN,22
2,571-85-3714,09-09-2024,12:14:00 AM,M. Semerad,Male,75,xray,Not Admission,NaN,16
3,404-43-9499,09-09-2024,8:33:00 PM,K. Blaydes,Male,79,xray,Admission,7.0,38
4,552-51-5855,09-09-2024,7:25:00 PM,F. Dickerson,Female,24,xray,Admission,7.0,36
...,...,...,...,...,...,...,...,...,...,...
9211,353-25-3957,01-01-2024,11:01:00 PM,S. Levermore,Male,19,Cardiology,Not Admission,NaN,34
9212,608-47-0337,01-01-2024,5:25:00 PM,R. Boyle,Female,22,Orthopedics,Admission,NaN,45
9213,716-90-5923,01-01-2024,11:42:00 AM,V. Seadon,Female,8,NaN,Admission,NaN,21
9214,641-52-3173,01-01-2024,4:59:00 AM,L. Harford,Female,37,NaN,Not Admission,5.0,10
9215,390-79-5650,01-01-2024,5:33:00 PM,E. Skerritt,Male,59,NaN,Not Admission,NaN,47

In [3]:
#cheking any null values present in the data
df.isnull().sum()

Patient Id                       0
Patient Admission Date           0
Patient Admission Time           0
patient name                     0
Patient Gender                   0
Patient Age                      0
Department Referral           5008
Patient Admission Flag           0
Patient Satisfaction Score    6696
Patient Waittime                 0
dtype: int64

In [5]:
#Cleaning the data for null values
df=df.dropna(subset=['Department Referral'])
df=df.dropna(subset=['Patient Satisfaction Score'])

In [6]:
df.isnull().sum()

Patient Id                    0
Patient Admission Date        0
Patient Admission Time        0
patient name                  0
Patient Gender                0
Patient Age                   0
Department Referral           0
Patient Admission Flag        0
Patient Satisfaction Score    0
Patient Waittime              0
dtype: int64

In [7]:
#Cheaking 10 rows 
df.head(10)

,Patient Id,Patient Admission Date,Patient Admission Time,patient name,Patient Gender,Patient Age,Department Referral,Patient Admission Flag,Patient Satisfaction Score,Patient Waittime
3,404-43-9499,09-09-2024,8:33:00 PM,K. Blaydes,Male,79,xray,Admission,7.0,38
4,552-51-5855,09-09-2024,7:25:00 PM,F. Dickerson,Female,24,xray,Admission,7.0,36
9,536-68-0475,09-09-2024,1:14:00 PM,T. Shillaker,Female,25,xray,Admission,6.0,14
12,223-54-0736,09-09-2024,12:34:00 PM,B. Carman,Female,51,xray,Admission,7.0,35
13,792-04-6423,09-09-2024,2:00:00 PM,K. Brittan,Female,59,xray,Admission,7.0,56
16,193-27-1560,09-09-2024,2:19:00 AM,E. Norcliff,Female,12,xray,Admission,6.0,17
25,552-80-5445,09-09-2023,12:28:00 PM,U. Bento,Female,17,xray,Not Admission,3.0,37
28,288-66-5811,09-09-2023,12:20:00 AM,K. Beseke,Male,63,xray,Not Admission,0.0,50
39,543-16-9617,09-08-2024,9:28:00 PM,U. Ervin,Male,79,xray,Admission,1.0,34
41,644-62-8312,09-08-2024,12:34:00 AM,O. Bille,Male,60,xray,Not Admission,4.0,28

In [8]:
#cheaking what are the columns present
df.columns

Index(['Patient Id', 'Patient Admission Date', 'Patient Admission Time',
       'patient name', 'Patient Gender', 'Patient Age', 'Department Referral',
       'Patient Admission Flag', 'Patient Satisfaction Score',
       'Patient Waittime'],
      dtype='str')

In [9]:
#Reducing the average waittime to 20 min
df["Improved Waittime"] = df["Patient Waittime"] - 20
df["Improved Waittime"] = df["Improved Waittime"].clip(lower=10)

print(df["Improved Waittime"].mean())

19.386655260906757

In [29]:
df["Admission_Time"] = pd.to_datetime(
    df["Patient_Admission_Time"],
    format="%I:%M:%S %p")

In [11]:
df["Hour"] = df["Admission_Time"].dt.hour

In [15]:
df.columns=df.columns.str.replace(' ','_')
df

,Patient_Id,Patient_Admission_Date,Patient_Admission_Time,patient_name,Patient_Gender,Patient_Age,Department_Referral,Patient_Admission_Flag,Patient_Satisfaction_Score,Patient_Waittime,Improved_Waittime,Admission_Time,Hour
3,404-43-9499,09-09-2024,8:33:00 PM,K. Blaydes,Male,79,xray,Admission,7.0,38,18,1900-01-01 20:33:00,20
4,552-51-5855,09-09-2024,7:25:00 PM,F. Dickerson,Female,24,xray,Admission,7.0,36,16,1900-01-01 19:25:00,19
9,536-68-0475,09-09-2024,1:14:00 PM,T. Shillaker,Female,25,xray,Admission,6.0,14,10,1900-01-01 13:14:00,13
12,223-54-0736,09-09-2024,12:34:00 PM,B. Carman,Female,51,xray,Admission,7.0,35,15,1900-01-01 12:34:00,12
13,792-04-6423,09-09-2024,2:00:00 PM,K. Brittan,Female,59,xray,Admission,7.0,56,36,1900-01-01 14:00:00,14
...,...,...,...,...,...,...,...,...,...,...,...,...,...
9172,344-07-4253,01-10-2024,7:50:00 AM,Q. Pinshon,Female,39,General Practice,Admission,2.0,44,24,1900-01-01 07:50:00,7
9180,204-42-0922,01-10-2024,6:46:00 PM,C. Pallin,Male,68,General Practice,Not Admission,3.0,56,36,1900-01-01 18:46:00,18
9186,241-06-7024,01-10-2023,3:44:00 PM,E. Cutress,Female,19,Physiotherapy,Admission,1.0,60,40,1900-01-01 15:44:00,15
9187,364-28-5162,01-10-2023,3:20:00 PM,I. De Ambrosis,Female,28,Cardiology,Not Admission,7.0,18,10,1900-01-01 15:20:00,15
9193,758-69-7526,01-10-2023,2:19:00 PM,Y. Durning,Female,13,General Practice,Admission,7.0,48,28,1900-01-01 14:19:00,14

In [16]:
admissions_by_hour = df.groupby("Hour").size()
print(admissions_by_hour)

Hour
0     53
1     43
2     59
3     54
4     49
5     46
6     44
7     44
8     49
9     49
10    43
11    41
12    46
13    51
14    42
15    50
16    46
17    46
18    59
19    50
20    45
21    52
22    41
23    67
dtype: int64

In [17]:
peak_hour = admissions_by_hour.idxmax()
peak_count = admissions_by_hour.max()

print("Peak admission hour:", peak_hour)
print("Number of admissions:", peak_count)

Peak admission hour: 23
Number of admissions: 67

In [24]:
max_age = df["Patient_Age"].max()

print("Maximum age:", max_age, "years")

Maximum age: 79 years

In [30]:
df.head(10)

,Patient_Id,Patient_Admission_Date,Patient_Admission_Time,patient_name,Patient_Gender,Patient_Age,Department_Referral,Patient_Admission_Flag,Patient_Satisfaction_Score,Patient_Waittime,Improved_Waittime,Admission_Time,Hour
3,404-43-9499,09-09-2024,8:33:00 PM,K. Blaydes,Male,79,xray,Admission,7.0,38,18,1900-01-01 20:33:00,20
4,552-51-5855,09-09-2024,7:25:00 PM,F. Dickerson,Female,24,xray,Admission,7.0,36,16,1900-01-01 19:25:00,19
9,536-68-0475,09-09-2024,1:14:00 PM,T. Shillaker,Female,25,xray,Admission,6.0,14,10,1900-01-01 13:14:00,13
12,223-54-0736,09-09-2024,12:34:00 PM,B. Carman,Female,51,xray,Admission,7.0,35,15,1900-01-01 12:34:00,12
13,792-04-6423,09-09-2024,2:00:00 PM,K. Brittan,Female,59,xray,Admission,7.0,56,36,1900-01-01 14:00:00,14
16,193-27-1560,09-09-2024,2:19:00 AM,E. Norcliff,Female,12,xray,Admission,6.0,17,10,1900-01-01 02:19:00,2
25,552-80-5445,09-09-2023,12:28:00 PM,U. Bento,Female,17,xray,Not Admission,3.0,37,17,1900-01-01 12:28:00,12
28,288-66-5811,09-09-2023,12:20:00 AM,K. Beseke,Male,63,xray,Not Admission,0.0,50,30,1900-01-01 00:20:00,0
39,543-16-9617,09-08-2024,9:28:00 PM,U. Ervin,Male,79,xray,Admission,1.0,34,14,1900-01-01 21:28:00,21
41,644-62-8312,09-08-2024,12:34:00 AM,O. Bille,Male,60,xray,Not Admission,4.0,28,10,1900-01-01 00:34:00,0

In [34]:
df['Patient_Admission'] = df['Patient_Admission_Flag']
df

,Patient_Id,Patient_Admission_Date,Patient_Admission_Time,patient_name,Patient_Gender,Patient_Age,Department_Referral,Patient_Admission_Flag,Patient_Satisfaction_Score,Patient_Waittime,Improved_Waittime,Admission_Time,Hour,Patient_Admission
3,404-43-9499,09-09-2024,8:33:00 PM,K. Blaydes,Male,79,xray,Admission,7.0,38,18,1900-01-01 20:33:00,20,Admission
4,552-51-5855,09-09-2024,7:25:00 PM,F. Dickerson,Female,24,xray,Admission,7.0,36,16,1900-01-01 19:25:00,19,Admission
9,536-68-0475,09-09-2024,1:14:00 PM,T. Shillaker,Female,25,xray,Admission,6.0,14,10,1900-01-01 13:14:00,13,Admission
12,223-54-0736,09-09-2024,12:34:00 PM,B. Carman,Female,51,xray,Admission,7.0,35,15,1900-01-01 12:34:00,12,Admission
13,792-04-6423,09-09-2024,2:00:00 PM,K. Brittan,Female,59,xray,Admission,7.0,56,36,1900-01-01 14:00:00,14,Admission
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9172,344-07-4253,01-10-2024,7:50:00 AM,Q. Pinshon,Female,39,General Practice,Admission,2.0,44,24,1900-01-01 07:50:00,7,Admission
9180,204-42-0922,01-10-2024,6:46:00 PM,C. Pallin,Male,68,General Practice,Not Admission,3.0,56,36,1900-01-01 18:46:00,18,Not Admission
9186,241-06-7024,01-10-2023,3:44:00 PM,E. Cutress,Female,19,Physiotherapy,Admission,1.0,60,40,1900-01-01 15:44:00,15,Admission
9187,364-28-5162,01-10-2023,3:20:00 PM,I. De Ambrosis,Female,28,Cardiology,Not Admission,7.0,18,10,1900-01-01 15:20:00,15,Not Admission
9193,758-69-7526,01-10-2023,2:19:00 PM,Y. Durning,Female,13,General Practice,Admission,7.0,48,28,1900-01-01 14:19:00,14,Admission